/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Clases.clsCat;
import Clases.clsDoctor;
import Clases.clsDog;
import Clases.clsVeterinary;
import controller.ctlPet;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author luisy
 */
public class frmPetManager extends javax.swing.JFrame {
    
    
    ctlPet ctlPet = new ctlPet();
   
    /**
     * Creates new form frmPetManager
     */
    public frmPetManager() {
        initComponents();
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearCat1 = new javax.swing.JButton();
        btnBuscarCat1 = new javax.swing.JButton();
        btnEditarCat1 = new javax.swing.JButton();
        btnEliminarCat1 = new javax.swing.JButton();
        lblPet = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        petList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCodeDog = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNameDog = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBornyearDog = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtColorDog = new javax.swing.JTextField();
        cmbHealthDog = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbBreedDog = new javax.swing.JComboBox<>();
        btnCrearDog = new javax.swing.JButton();
        btnBuscarDog = new javax.swing.JButton();
        btnEditarDog = new javax.swing.JButton();
        btnEliminarDog = new javax.swing.JButton();
        checkBoxDog = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        txtPetid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodeCat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNameCat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBornyearCat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtColorCat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCrearCat = new javax.swing.JButton();
        btnBuscarCat = new javax.swing.JButton();
        btnEditarCat = new javax.swing.JButton();
        btnEliminarCat = new javax.swing.JButton();
        cmbHealthCat = new javax.swing.JComboBox<>();
        cmbBreedCat = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtPetid2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDoctor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnCrearDoctor = new javax.swing.JButton();
        btnBuscarDoctor = new javax.swing.JButton();
        btnEditarDoctor = new javax.swing.JButton();
        btnEliminarDoctor = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNombreVet = new javax.swing.JTextField();
        txtTelefonoVet = new javax.swing.JTextField();
        txtDirVet = new javax.swing.JTextField();
        cmbDoctor = new javax.swing.JComboBox<>();
        btnCrearVet = new javax.swing.JButton();
        btnBuscarVet = new javax.swing.JButton();
        btnEditarVet = new javax.swing.JButton();
        btnEliminarVet = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtCodeVet = new javax.swing.JTextField();

        btnCrearCat1.setText("Crear");
        btnCrearCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCat1ActionPerformed(evt);
            }
        });

        btnBuscarCat1.setText("Buscar");
        btnBuscarCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCat1ActionPerformed(evt);
            }
        });

        btnEditarCat1.setText("Editar");
        btnEditarCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCat1ActionPerformed(evt);
            }
        });

        btnEliminarCat1.setText("Eliminar");
        btnEliminarCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCat1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblPet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPet.setText("Pet Manager");

        jTabbedPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VeterinaryManagerClicked(evt);
            }
        });

        petList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pet1", "Pet2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(petList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Pet List", jPanel1);

        jLabel8.setText("codigo");

        txtCodeDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeDogActionPerformed(evt);
            }
        });

        jLabel9.setText("Name");

        jLabel10.setText("Health Status");

        jLabel11.setText("Born Year");

        txtBornyearDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBornyearDogActionPerformed(evt);
            }
        });

        jLabel12.setText("Color");

        txtColorDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorDogActionPerformed(evt);
            }
        });

        cmbHealthDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Healthy", "Sick", "In Surgery", "Hospital" }));

        jLabel13.setText("Breed");

        cmbBreedDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pitbull", "Doberman", "Shiba", "Criollo", "French Puddle" }));

        btnCrearDog.setText("Crear");
        btnCrearDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDogActionPerformed(evt);
            }
        });

        btnBuscarDog.setText("Buscar");
        btnBuscarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDogActionPerformed(evt);
            }
        });

        btnEditarDog.setText("Editar");
        btnEditarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDogActionPerformed(evt);
            }
        });

        btnEliminarDog.setText("Eliminar");
        btnEliminarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDogActionPerformed(evt);
            }
        });

        checkBoxDog.setText("Pedigree");
        checkBoxDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDogActionPerformed(evt);
            }
        });

        jLabel20.setText("PETID");

        txtPetid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPetidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbHealthDog, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNameDog, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                            .addComponent(txtCodeDog)
                                            .addComponent(txtPetid, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnCrearDog)
                                .addGap(52, 52, 52)
                                .addComponent(btnBuscarDog)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBornyearDog, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                            .addComponent(txtColorDog)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbBreedDog, 0, 123, Short.MAX_VALUE)
                                        .addGap(37, 37, 37)))
                                .addGap(3, 3, 3)
                                .addComponent(checkBoxDog)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnEditarDog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addComponent(btnEliminarDog)
                                .addGap(67, 67, 67))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodeDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtBornyearDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNameDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtColorDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtPetid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbHealthDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cmbBreedDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxDog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearDog)
                    .addComponent(btnBuscarDog)
                    .addComponent(btnEditarDog)
                    .addComponent(btnEliminarDog))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane3.addTab("Dog Manager", jPanel2);

        jLabel2.setText("codigo");

        txtCodeCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeCatActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Health Status");

        jLabel5.setText("Born Year");

        txtBornyearCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBornyearCatActionPerformed(evt);
            }
        });

        jLabel6.setText("Color");

        txtColorCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorCatActionPerformed(evt);
            }
        });

        jLabel7.setText("Breed");

        btnCrearCat.setText("Crear");
        btnCrearCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCatActionPerformed(evt);
            }
        });

        btnBuscarCat.setText("Buscar");
        btnBuscarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCatActionPerformed(evt);
            }
        });

        btnEditarCat.setText("Editar");
        btnEditarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCatActionPerformed(evt);
            }
        });

        btnEliminarCat.setText("Eliminar");
        btnEliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCatActionPerformed(evt);
            }
        });

        cmbHealthCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Healthy", "Sick", "In Surgery", "Hospital" }));

        cmbBreedCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Angora", "Persa", "Siamés", "Chartreux" }));

        jLabel21.setText("petid");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnCrearCat)
                                .addGap(52, 52, 52)
                                .addComponent(btnBuscarCat))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNameCat, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                            .addComponent(txtCodeCat)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbHealthCat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPetid2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBornyearCat, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(txtColorCat))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnEditarCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarCat)
                                .addGap(67, 67, 67))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(33, 33, 33)
                                .addComponent(cmbBreedCat, 0, 85, Short.MAX_VALUE)
                                .addGap(82, 82, 82))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodeCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtBornyearCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNameCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtColorCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbHealthCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbBreedCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPetid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCat)
                    .addComponent(btnBuscarCat)
                    .addComponent(btnEditarCat)
                    .addComponent(btnEliminarCat))
                .addGap(47, 47, 47))
        );

        jTabbedPane3.addTab("Cat Manager", jPanel3);

        jLabel1.setText("Nombre Doctor");

        jLabel14.setText("Phone");

        btnCrearDoctor.setText("Crear");
        btnCrearDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDoctorActionPerformed(evt);
            }
        });

        btnBuscarDoctor.setText("Buscar");
        btnBuscarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDoctorActionPerformed(evt);
            }
        });

        btnEditarDoctor.setText("Editar");
        btnEditarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDoctorActionPerformed(evt);
            }
        });

        btnEliminarDoctor.setText("Eliminar");
        btnEliminarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDoctorActionPerformed(evt);
            }
        });

        jLabel22.setText("Address");

        jLabel23.setText("code (generado)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel14)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txtAddress)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnCrearDoctor)
                        .addGap(52, 52, 52)
                        .addComponent(btnBuscarDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(btnEditarDoctor)
                        .addGap(72, 72, 72)))
                .addComponent(btnEliminarDoctor)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearDoctor)
                    .addComponent(btnBuscarDoctor)
                    .addComponent(btnEditarDoctor)
                    .addComponent(btnEliminarDoctor))
                .addGap(74, 74, 74))
        );

        jTabbedPane3.addTab("Doctor Manager", jPanel5);

        jLabel15.setText("nombre");

        jLabel16.setText("telefono");

        jLabel17.setText("dirección");

        jLabel18.setText("doctor encargado");

        btnCrearVet.setText("Crear");
        btnCrearVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVetActionPerformed(evt);
            }
        });

        btnBuscarVet.setText("Buscar");
        btnBuscarVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVetActionPerformed(evt);
            }
        });

        btnEditarVet.setText("Editar");
        btnEditarVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarVetActionPerformed(evt);
            }
        });

        btnEliminarVet.setText("Eliminar");
        btnEliminarVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVetActionPerformed(evt);
            }
        });

        jLabel19.setText("DEBE EXISTIR UN DOCTOR PRIMERO");

        jLabel24.setText("codigo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrearVet)
                .addGap(52, 52, 52)
                .addComponent(btnBuscarVet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(btnEditarVet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnEliminarVet)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreVet)
                            .addComponent(txtTelefonoVet)
                            .addComponent(txtDirVet)
                            .addComponent(cmbDoctor, 0, 145, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel19))
                    .addComponent(txtCodeVet, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNombreVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtTelefonoVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtDirVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtCodeVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearVet)
                    .addComponent(btnBuscarVet)
                    .addComponent(btnEditarVet)
                    .addComponent(btnEliminarVet))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Veterinary Manager", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(lblPet))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblPet)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeCatActionPerformed

    private void txtBornyearCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBornyearCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBornyearCatActionPerformed

    private void txtColorCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorCatActionPerformed

    private void btnBuscarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCatActionPerformed
        // TODO add your handling code here:
        String codeCat = txtCodeCat.getText();
        clsCat dog = (clsCat) ctlPet.searchPet(codeCat, "Gato");
        if (dog==null){
            JOptionPane.showMessageDialog(null, "Not found! ");
        }else{
            txtNameCat.setText(dog.getName());
               txtColorCat.setText(dog.getColor());
               txtBornyearCat.setText((Integer.toString(dog.getBorn_year())));
               cmbHealthCat.setSelectedItem(dog.getHealth_status());
               cmbBreedCat.setSelectedItem(dog.getBreed());
               txtPetid2.setText(Integer.toString(dog.getCatId()));
               
        }
    }//GEN-LAST:event_btnBuscarCatActionPerformed

    private void txtCodeDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeDogActionPerformed

    private void txtBornyearDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBornyearDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBornyearDogActionPerformed

    private void txtColorDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorDogActionPerformed

    private void btnBuscarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDogActionPerformed
        // TODO add your handling code here:
        String codeDog = txtCodeDog.getText();
        clsDog dog = (clsDog) ctlPet.searchPet(codeDog, "Perro");
        if (dog==null){
            JOptionPane.showMessageDialog(null, "Not found! ");
        }else{
            txtNameDog.setText(dog.getName());
               txtColorDog.setText(dog.getColor());
               txtBornyearDog.setText((Integer.toString(dog.getBorn_year())));
               cmbHealthDog.setSelectedItem(dog.getHealth_status());
               cmbBreedDog.setSelectedItem(dog.getBreed());
               checkBoxDog.setSelected(dog.isPedigree());
               txtPetid.setText(Integer.toString(dog.getDogId()));
        }
        /*System.out.println("CODE ISS "+ codeDog);
        boolean found = false;
        for(clsDog dog : petlist){
           System.out.println("CODE om iteration "+ dog.getCode());
           if(dog.getCode().equals(codeDog)){
               System.out.println("ENOCNT´RE EL PERRO!!");
               txtNameDog.setText(dog.getName());
               txtColorDog.setText(dog.getColor());
               txtBornyearDog.setText((Integer.toString(dog.getBorn_year())));
               cmbHealthDog.setSelectedItem(dog.getHealth_status());
               cmbBreedDog.setSelectedItem(dog.getBreed());
               checkBoxDog.setSelected(dog.isPedigree());
               found = true;
               break;
           }
           
        }*/
        
    }//GEN-LAST:event_btnBuscarDogActionPerformed

    private void checkBoxDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxDogActionPerformed

    private void btnCrearDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDogActionPerformed
        // TODO add your handling code here:
        try{
            String codeDog = txtCodeDog.getText();
        String nameDog = txtNameDog.getText();
        int bornDog = Integer.parseInt(txtBornyearDog.getText());
        String color = txtColorDog.getText();
        
        String breed = (String) cmbBreedDog.getSelectedItem();
        String health = (String) cmbHealthDog.getSelectedItem();
        boolean pedigree = checkBoxDog.isSelected();
        
        if(codeDog.equals("") || nameDog.equals("") || color.equals("")){
            JOptionPane.showMessageDialog(this, "Empty fields! ");
        }
        else{
            clsDog dog = new clsDog(breed, pedigree, codeDog, nameDog, bornDog, color, health);
            boolean r = ctlPet.createPet(dog);
        if (r){
            JOptionPane.showMessageDialog(this, "Perrito agregado :) ");
            this.clearDogFields();
            FillJList();
        }else{
            JOptionPane.showMessageDialog(this, "No se agregó! ");
        }
        
        
        
        }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btnCrearDogActionPerformed

    private void btnEditarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDogActionPerformed
        // TODO add your handling code here:
        String codeDog = txtCodeDog.getText();
        int petid = Integer.parseInt(txtPetid.getText());
        String nameDog = txtNameDog.getText();
        int bornDog = Integer.parseInt(txtBornyearDog.getText());
        String color = txtColorDog.getText();
        
        String breed = (String) cmbBreedDog.getSelectedItem();
        String health = (String) cmbHealthDog.getSelectedItem();
        boolean pedigree = checkBoxDog.isSelected();
        
        clsDog pet = new clsDog(petid, breed, pedigree, codeDog, nameDog, bornDog, color, health);
        boolean found = ctlPet.editPet(pet);
        if(found){
            JOptionPane.showMessageDialog(null, "Record updated succesfully! ");
            this.clearDogFields();
            this.FillJList();
        }else{
            
        }

        if (!found){
            JOptionPane.showMessageDialog(null, "Not found, not edited! ");
        }
    }//GEN-LAST:event_btnEditarDogActionPerformed

    private void btnEliminarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDogActionPerformed
        // TODO add your handling code here:
        String codeDog = txtCodeDog.getText();
        boolean found = false;
        clsDog pet = (clsDog) ctlPet.searchPet(codeDog, "Perro");
        if(pet!=null){
            found = ctlPet.deletePet(pet);
            if (found){
                JOptionPane.showMessageDialog(null, "Record DELETED succesfully! ");
                this.clearDogFields();
                this.FillJList();
            }
            else{
                JOptionPane.showMessageDialog(null, "Not found, not deleted! ");
            }
            
        }else{
            
        }
        

    }//GEN-LAST:event_btnEliminarDogActionPerformed

    private void btnCrearCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCatActionPerformed
        // TODO add your handling code here:
        try{
           
        String codeCat = txtCodeCat.getText();
        String nameCat = txtNameCat.getText();
        int bornCat = Integer.parseInt(txtBornyearCat.getText());
        String color = txtColorCat.getText();
        
        String breed = (String) cmbBreedCat.getSelectedItem();
        String health = (String) cmbHealthCat.getSelectedItem();
        
        
        if(codeCat.equals("") || nameCat.equals("") || color.equals("")){
            JOptionPane.showMessageDialog(this, "Empty fields! ");
        }
        else{
        clsCat cat = new clsCat(codeCat, nameCat, bornCat, color, health, breed);
        ctlPet.createPet(cat);
        
        JOptionPane.showMessageDialog(this, "Gatito agregado :) ");
        this.clearCatFields();
        FillJList();
        }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please add a valid year ");
        }
    }//GEN-LAST:event_btnCrearCatActionPerformed

    private void btnEditarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCatActionPerformed
        // TODO add your handling code here:
        String codeDog = txtCodeCat.getText();
        int petid = Integer.parseInt(txtPetid2.getText());
        String nameDog = txtNameCat.getText();
        int bornDog = Integer.parseInt(txtBornyearCat.getText());
        String color = txtColorCat.getText();
        
        String breed = (String) cmbBreedCat.getSelectedItem();
        String health = (String) cmbHealthCat.getSelectedItem();
        
        
        clsCat pet = new clsCat(petid, breed, codeDog,  nameDog, bornDog, color, health);
        boolean found = ctlPet.editPet(pet);
        if(found){
            JOptionPane.showMessageDialog(null, "Record updated succesfully! ");
            this.clearDogFields();
            this.FillJList();
        }else{
            
        }

        if (!found){
            JOptionPane.showMessageDialog(null, "Not found, not edited! ");
        }
    }//GEN-LAST:event_btnEditarCatActionPerformed

    private void btnEliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCatActionPerformed
        // TODO add your handling code here:
        String codeDog = txtCodeCat.getText();
        boolean found = false;
        clsCat pet = (clsCat) ctlPet.searchPet(codeDog, "Gato");
        if(pet!=null){
            found = ctlPet.deletePet(pet);
            if (found){
                JOptionPane.showMessageDialog(null, "Record DELETED succesfully! ");
                this.clearCatFields();
                this.FillJList();
            }
            else{
                JOptionPane.showMessageDialog(null, "Not found, not deleted! ");
            }
            
        }else{
            
        }
    }//GEN-LAST:event_btnEliminarCatActionPerformed

    private void btnCrearCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearCat1ActionPerformed

    private void btnBuscarCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCat1ActionPerformed

    private void btnEditarCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarCat1ActionPerformed

    private void btnEliminarCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCat1ActionPerformed

    private void btnCrearDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDoctorActionPerformed
        // TODO add your handling code here:
        try{
            String name = txtDoctor.getText();
            String phone = txtPhone.getText();
            String address = txtAddress.getText();
            if(name.equals("") || phone.equals("")|| address.equals("")){
            JOptionPane.showMessageDialog(this, "Empty fields! ");
        }
        else{
        clsDoctor doctor = new clsDoctor(name, phone, address);
        ctlPet.createDoctor(doctor);
        
        JOptionPane.showMessageDialog(this, "Doctor agregado! ");
        this.clearDocFields();
        FillJList();
        }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btnCrearDoctorActionPerformed

    private void btnBuscarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDoctorActionPerformed
        // TODO add your handling code here:
        int codeDoc = Integer.parseInt(txtCode.getText());
        clsDoctor doc = ctlPet.searchDoc(codeDoc);
        if (doc==null){
            JOptionPane.showMessageDialog(null, "Not found! ");
        }else{
            txtDoctor.setText(doc.getName());
            txtPhone.setText(doc.getPhone());
            txtAddress.setText(doc.getAddress());
            txtCode.setText(Integer.toString(doc.getDoctorId()));
        }
    }//GEN-LAST:event_btnBuscarDoctorActionPerformed

    private void btnEditarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDoctorActionPerformed
        // TODO add your handling code here:
        int code = Integer.parseInt(txtCode.getText());
        String name = txtDoctor.getText();
        String phone  = txtPhone.getText();
        String address = txtAddress.getText();
        
        clsDoctor doc = new clsDoctor(code, name, phone, address);
        boolean found = ctlPet.editDoctor(doc);
        if(found){
            JOptionPane.showMessageDialog(null, "Record updated succesfully! ");
            this.clearDogFields();
            this.FillJList();
        }else{
            
        }

        if (!found){
            JOptionPane.showMessageDialog(null, "Not found, not edited! ");
        }
        
    }//GEN-LAST:event_btnEditarDoctorActionPerformed

    private void btnEliminarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDoctorActionPerformed
        // TODO add your handling code here:
       int code = Integer.parseInt(txtCode.getText());
        boolean found = false;
        clsDoctor doc = ctlPet.searchDoc(code);
        if(doc!=null){
            found = ctlPet.deleteDoctor(doc);
            if (found){
                JOptionPane.showMessageDialog(null, "Record DELETED succesfully! ");
                this.clearDocFields();
                this.FillJList();
            }
            else{
                JOptionPane.showMessageDialog(null, "Not found, not deleted! ");
            }
            
        }else{
            
        }
    }//GEN-LAST:event_btnEliminarDoctorActionPerformed

    private void btnCrearVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVetActionPerformed
        // TODO add your handling code here:
        try{
            String nombre = txtNombreVet.getText();
            String phone = txtTelefonoVet.getText();
            String address = txtDirVet.getText();
            int doctorid =  Integer.parseInt((((String) cmbDoctor.getSelectedItem())).split("-")[0]);
            clsDoctor doctor = ctlPet.searchDoc(doctorid);
            
            if(nombre.equals("") || phone.equals("")|| address.equals("")){
            JOptionPane.showMessageDialog(this, "Empty fields! ");
        }
        else{
                clsVeterinary vet = new clsVeterinary(nombre, phone, address, doctor);
                ctlPet.createVet(vet);
        
        JOptionPane.showMessageDialog(this, "Veterinaria agregada! ");
        this.clearVetFields();
        FillJList();
        }
        }catch(Exception e){
            System.out.println("ERROR" +e);
        }
    }//GEN-LAST:event_btnCrearVetActionPerformed

    private void btnBuscarVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVetActionPerformed
        // TODO add your handling code here:
        
        String id = txtCodeVet.getText();
        clsVeterinary vet = ctlPet.searchVet(Integer.parseInt(id));
        if (vet==null){
            JOptionPane.showMessageDialog(null, "Not found! ");
        }else{
            txtNombreVet.setText(vet.getName());
            txtDirVet.setText(vet.getAddress());
            txtTelefonoVet.setText(vet.getPhone());
           this.cmbDoctor.setSelectedItem(vet.getDoctor().getDoctorId()+"-"+vet.getDoctor().getName());
        }
    }//GEN-LAST:event_btnBuscarVetActionPerformed

    private void btnEditarVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarVetActionPerformed
        // TODO add your handling code here:
            int idvet = Integer.parseInt(txtCodeVet.getText());
            String nombre = txtNombreVet.getText();
            String phone = txtTelefonoVet.getText();
            String address = txtDirVet.getText();
            int doctorid =  Integer.parseInt((((String) cmbDoctor.getSelectedItem())).split("-")[0]);
            clsDoctor doctor = ctlPet.searchDoc(doctorid);
            
            if(nombre.equals("") || phone.equals("")|| address.equals("")){
                JOptionPane.showMessageDialog(this, "Empty fields! ");
            }
        clsVeterinary vet = new clsVeterinary(idvet, nombre, phone, address, doctor);
        boolean found = ctlPet.editVet(vet);
        if(found){
            JOptionPane.showMessageDialog(null, "Record updated succesfully! ");
            this.clearVetFields();
            this.FillJList();
        }else{
            
        }

        if (!found){
            JOptionPane.showMessageDialog(null, "Not found, not edited! ");
        }
    }//GEN-LAST:event_btnEditarVetActionPerformed

    private void btnEliminarVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVetActionPerformed
        // TODO add your handling code here:
        String id = txtCodeVet.getText();
        clsVeterinary vet = ctlPet.searchVet(Integer.parseInt(id));
        boolean found = false;
        if(vet!=null){
            found = ctlPet.deleteVet(vet);
            if (found){
                JOptionPane.showMessageDialog(null, "Record DELETED succesfully! ");
                this.clearVetFields();
                this.FillJList();
            }
            else{
                JOptionPane.showMessageDialog(null, "Not found, not deleted! ");
            }
            
        }else{
            
        }
    }//GEN-LAST:event_btnEliminarVetActionPerformed

    private void VeterinaryManagerClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VeterinaryManagerClicked
        // TODO add your handling code here:
        cmbDoctor.removeAllItems();
        
        for (clsDoctor doc: ctlPet.getDocList()){
            this.cmbDoctor.addItem(doc.getDoctorId()+"-"+doc.getName());
        }
        
    }//GEN-LAST:event_VeterinaryManagerClicked

    private void txtPetidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPetidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPetidActionPerformed

    
    private void FillJList(){
        DefaultListModel model = new DefaultListModel();
        int index  =0;
        for (clsDog dog: ctlPet.getDogList("Perro")){
            String data  = dog.getName() + " "+ dog.getBreed() + " (PERRO)";
            model.add(index, data);
            index++;
        }
        
        for (clsCat cat: ctlPet.getCatList("Gato")){
            String data  = cat.getName() + " "+ cat.getBreed() + " (GATO)";
            model.add(index, data);
            index++;
        }
        
        for (clsDoctor doc: ctlPet.getDocList()){
            //String data  = doc.getName() + " "+ doc.getLicense() + " (DOCTOR)";
            //model.add(index, data);
            index++;
        }
        
        for (clsVeterinary v: ctlPet.getVetList()){
            String data  = v.getName() + " "+ v.getPhone()+ " "+ v.getAddress() + " (VETERINARIA)";
            model.add(index, data);
            index++;
        }
        
        petList.setModel(model);
    }
    
    private void clearDogFields(){
        txtNameDog.setText("");
        txtBornyearDog.setText("");
        txtCodeDog.setText("");
        txtColorDog.setText("");
        
    }
    
    private void clearCatFields(){
        txtNameCat.setText("");
        txtBornyearCat.setText("");
        txtCodeCat.setText("");
        txtColorCat.setText("");
        
    }
    
    private void clearDocFields() {
        txtDoctor.setText("");
        txtPhone.setText("");
    }
    
    private void clearVetFields() {
        txtNombreVet.setText("");
        txtTelefonoVet.setText("");
        txtDirVet.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPetManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPetManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPetManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPetManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPetManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCat;
    private javax.swing.JButton btnBuscarCat1;
    private javax.swing.JButton btnBuscarDoctor;
    private javax.swing.JButton btnBuscarDog;
    private javax.swing.JButton btnBuscarVet;
    private javax.swing.JButton btnCrearCat;
    private javax.swing.JButton btnCrearCat1;
    private javax.swing.JButton btnCrearDoctor;
    private javax.swing.JButton btnCrearDog;
    private javax.swing.JButton btnCrearVet;
    private javax.swing.JButton btnEditarCat;
    private javax.swing.JButton btnEditarCat1;
    private javax.swing.JButton btnEditarDoctor;
    private javax.swing.JButton btnEditarDog;
    private javax.swing.JButton btnEditarVet;
    private javax.swing.JButton btnEliminarCat;
    private javax.swing.JButton btnEliminarCat1;
    private javax.swing.JButton btnEliminarDoctor;
    private javax.swing.JButton btnEliminarDog;
    private javax.swing.JButton btnEliminarVet;
    private javax.swing.JCheckBox checkBoxDog;
    private javax.swing.JComboBox<String> cmbBreedCat;
    private javax.swing.JComboBox<String> cmbBreedDog;
    private javax.swing.JComboBox<String> cmbDoctor;
    private javax.swing.JComboBox<String> cmbHealthCat;
    private javax.swing.JComboBox<String> cmbHealthDog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblPet;
    private javax.swing.JList<String> petList;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBornyearCat;
    private javax.swing.JTextField txtBornyearDog;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCodeCat;
    private javax.swing.JTextField txtCodeDog;
    private javax.swing.JTextField txtCodeVet;
    private javax.swing.JTextField txtColorCat;
    private javax.swing.JTextField txtColorDog;
    private javax.swing.JTextField txtDirVet;
    private javax.swing.JTextField txtDoctor;
    private javax.swing.JTextField txtNameCat;
    private javax.swing.JTextField txtNameDog;
    private javax.swing.JTextField txtNombreVet;
    private javax.swing.JTextField txtPetid;
    private javax.swing.JTextField txtPetid2;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTelefonoVet;
    // End of variables declaration//GEN-END:variables

    
}
